const DirectoryActionTypes = {
  FETCH_ITEMS_START: 'FETCH_ITEMS_START',
  FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
  FETCH_ITEMS_FAILURE: 'FETCH_ITEMS_FAILURE',
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  ADD_CATEGORY_FILTER: 'ADD_CATEGORY_FILTER',
  REMOVE_CATEGORY_FILTER: 'REMOVE_CATEGORY_FILTER',
  RESET_CATEGORY_FILTERS: 'RESET_CATEGORY_FILTERS',
  TOGGLE_TODO_FILTER: 'TOGGLE_TODO_FILTER',
  ADD_STATUS_FILTER: 'ADD_STATUS_FILTER',
  REMOVE_STATUS_FILTER: 'REMOVE_STATUS_FILTER',
  SET_ITEMS: 'SET_ITEMS',
  CHANGE_FILTER_TYPE: 'CHANGE_FILTER_TYPE',

};

export default DirectoryActionTypes;
