const ItemActionTypes = {
  SET_ITEM: 'SET_ITEM',
  FETCH_ITEM_CATEGORIES_START: 'FETCH_ITEM_CATEGORIES_START',
  FETCH_ITEM_CATEGORIES_SUCCESS: 'FETCH_ITEM_CATEGORIES_SUCCESS',
  FETCH_ITEM_CATEGORIES_FAILURE: 'FETCH_ITEM_CATEGORIES_FAILURE',
};

export default ItemActionTypes;
